apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium-helm-repo
        namespace: cilium
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values if needed later
  #values:
   