apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world-app
  namespace: hello-world
spec:
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: hello-world
  path: ./gitops/apps/helloworld
  prune: true
  wait: true