apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  timeout: 5m0s
  interval: 10m0s
  # dependsOn:
  #   - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/controllers
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  interval: 10m0s
  # dependsOn:
  #   - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/clusters/TalosCluster/configs
  prune: true
  wait: true