apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n-release
  namespace: n8n
spec:
  interval: 30m
  chart:
    spec:
      chart: n8n
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: n8n-repository
        namespace: flux-system
      interval: 12h
  values:
    worker:
      mode: queue
      persistence:
        enabled: true
        volumeName: "n8n-worker-data"
        mountPath: "/home/node/.n8n"
        size: 5Gi
        accessMode: ReadWriteMany  # For autoscaling
        storageClass: "main-nfs"
      # autoscaling:
      #   enable: true
    main:
      persistence:
        enabled: true
        volumeName: "n8n-main-data"
        mountPath: "/home/node/.n8n"
        size: 8Gi
        accessMode: ReadWriteOnce
        storageClass: "main-nfs"
        annotations:
          helm.sh/resource-policy: keep