---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab-postgresql-repo
  namespace: gitlab
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-postgresql-release
  namespace: gitlab
spec:
  interval: 30m
  chart:
    spec:
      chart: cnpg
      version: "x"
      sourceRef:
        kind: HelmRepository
        name: gitlab-postgresql-repo
        namespace: gitlab
      interval: 12h
  values:
    config:
      clusterWide: false
      