---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    toolkit.fluxcd.io/tenant: mytenant
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-stack
  namespace: observability
spec:
  interval: 24h
  url: https://kubernetes.github.io/prometheus-stack
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-stack
        namespace: observability
      interval: 12h
  # values:
  #   controller:
  #     service:
  #       type: "NodePort"
  #   admissionWebhooks:
  #     enabled: false