apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hello-world-test-gateway
  namespace: hello-world
spec:
  gatewayClassName: nginx
  listeners:
  - protocol: HTTP
    port: 80
    name:  hello-world-test-gateway
    allowedRoutes:
      namespaces:
        from: Same

---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: nginx
spec:
  controllerName: "k8s.ingress-nginx.io/gateway-controller"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world-route
  namespace: hello-world
spec:
  parentRefs:
  - name: hello-world-test-gateway
  rules:
  - backendRefs:
    - name: foo-svc
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-deployment
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
        namespace: hello-world
    spec:
      containers:
      - name: hello-nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: foo-svc
  namespace: hello-world
spec:
  selector:
    app: hello-nginx
  ports:
  - name: http
    port: 8080        # the port referenced by HTTPRoute
    targetPort: 80    # container port exposed by nginxdemos/hello